### ISSUE TITLE
Do you know iced_x86 has leaks?

### ISSUE THREAD

**Issue by persytry** [regomne/ilhook-rs#10]
[iced leaks](https://github.com/icedland/iced/issues/552)

Do you want to change iced-x86 to udis86?

**Comment by regomne** [comment]
It seems that iced-x86 has memory leaks only on kernel mode. But ilhook-rs does not support no_std right now.
I will change it if I am going to support no_std.

**Comment by regomne** [comment]
I'm considering to change it later when I have time. Or maybe you could commit a pull request?

**Comment by persytry** [comment]
I tried it, I failed, it's hard for me, because ilhook depend on iced many places

**Comment by regomne** [comment]
Yeah, it's a big project.
