### ISSUE TITLE
it seems like doesn't work

### ISSUE THREAD

**Issue by yangrudan** [regomne/ilhook-rs#15]
![image](https://github.com/user-attachments/assets/8c9f32e7-b061-4001-bec0-cc99c849cf81)

```
❯ uname -a
Linux ThinkpadX1 6.8.0-47-generic #47-Ubuntu SMP PREEMPT_DYNAMIC Fri Sep 27 21:40:26 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux
```

```rust
use ilhook::x64::{Hooker, HookType, Registers, CallbackOption, HookFlags};

fn target_function(x: i32) -> i32 {
    x * x
}

// 修改回调函数签名和实现
unsafe extern "win64" fn hook_callback(
    reg: *mut Registers,
    _: usize,
    _: usize
) -> usize {
    let x = (&*reg).rcx as i32;  // 在 x64 上第一个参数在 rcx 中
    println!("Hook triggered with x = {}", x);
    (x * x + 10) as usize
}


fn main() {
    let addr = target_function as usize;

    let hooker = Hooker::new(
        addr,
        HookType::Retn(hook_callback),
        CallbackOption::None,
        0,
        HookFlags::empty()
    );

    match unsafe { hooker.hook() } {
        Ok(_) => println!("Hook installed successfully"),
        Err(e) => println!("Hook installation failed: {:?}", e),
    }

    let result = target_function(5);
    println!("Result: {}", result);
}
```

**Output**
![image](https://github.com/user-attachments/assets/a4b79f86-0b12-423c-84b8-0c128d24706f)

Why dosen't it work?

Looking forward for your reply~

**Comment by regomne** [comment]
Hooker::hook returns a HookPoint, which manages the lifecyle of the hook point. The hook point will be restored when HookPoint destructs.
Please ensure the HookPoint lives long enough before calling the be-hooked function.

Btw, RCX stores the 1st argument only in win64 ABI, while linux uses the sysv64 ABI which uses the RDI to pass the 1st argument.

**Comment by yangrudan** [comment]
> sysv64

Is this the modification?

![image](https://github.com/user-attachments/assets/2623eed6-923c-45e6-b562-441237359b58)

**Comment by regomne** [comment]
I think you need to have some knowledge of hook and calling convention before using this library. You may get more problems without that.

**Comment by yangrudan** [comment]
> I think you need to have some knowledge of hook and calling convention before using this library. You may get more problems without that.

Thank you for your reply, I will add relevant knowledge, the purpose of this issue is to know whether the hook under Linux is supported?

**Comment by regomne** [comment]
Yes, linux is supported.

**Comment by yangrudan** [comment]
> Yes, linux is supported.

Ok, I'll close it first, and try to use it, then open it if there's a problem.
