### ISSUE TITLE
"Hooker::new" support "extra_data"

### ISSUE THREAD

**Issue by persytry** [regomne/ilhook-rs#4]
Could you support "extra_data" for Hooker::new function?
Then, pass the "extra_data" to callback of HookType, example: 
```rust
pub type JmpBackRoutine = unsafe extern "win64" fn(regs: *mut Registers, src_addr: usize, extra_data: *const u8);
````
thanks.

**Comment by regomne** [comment]
Yeah, that is a useful feature. I will add it next week.

**Comment by persytry** [comment]
Thank you

**Comment by regomne** [comment]
Feature added. The parameter `src_addr` in callbacks is replaced by `user_data` which is passed previously to `Hooker::new`.

**Comment by persytry** [comment]
Thank you， great

**Comment by persytry** [comment]
Are not you published v2.0 to the crates.io? I want to use the new feature, that's exciting!

**Comment by regomne** [comment]
https://crates.io/crates/ilhook
From the webpage, it has been published.

**Comment by persytry** [comment]
thanks
