### ISSUE TITLE
Missing LICENSE

### ISSUE THREAD

**Issue by slavfox** [regomne/ilhook-rs#7]
Hello! The project's [cargo.toml](https://github.com/regomne/ilhook-rs/blob/master/Cargo.toml) specifies `license = "MIT"`, but there is no LICENSE present in the repository.

Since the MIT license includes a copyright notice and requires it be preserved:

> Copyright \<YEAR> \<COPYRIGHT HOLDER>
> 
> Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the “Software”), to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, subject to the following conditions:
> 
> The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.

There is no clear way to obey the requirements of the license when using `ilhook-rs`. Could you add a LICENSE file including a copyright notice, so that `ilhook-rs` may be properly attributed?

**Comment by regomne** [comment]
Thank you. I added the license file.
